'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("312, 241")>  _
        Public Property table1_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table1_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table1_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("122, 60")>  _
        Public Property table1_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table1_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table1_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("312, 182")>  _
        Public Property table2_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table2_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table2_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("122, 60")>  _
        Public Property table2_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table2_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table2_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("312, 123")>  _
        Public Property table3_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table3_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table3_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("122, 60")>  _
        Public Property table3_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table3_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table3_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("482, 126")>  _
        Public Property table4_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table4_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table4_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70, 101")>  _
        Public Property table4_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table4_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table4_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("551, 126")>  _
        Public Property table5_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table5_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table5_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70, 101")>  _
        Public Property table5_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table5_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table5_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("621, 126")>  _
        Public Property table6_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table6_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table6_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70, 101")>  _
        Public Property table6_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table6_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table6_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("691, 126")>  _
        Public Property table7_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table7_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table7_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70, 101")>  _
        Public Property table7_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table7_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table7_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("747, 29")>  _
        Public Property table8_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table8_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table8_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("79, 54")>  _
        Public Property table8_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table8_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table8_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("747, 280")>  _
        Public Property table9_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table9_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table9_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("79, 54")>  _
        Public Property table9_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table9_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table9_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("181, 30")>  _
        Public Property table10_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("table10_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("table10_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("101, 60")>  _
        Public Property table10_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("table10_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("table10_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12, 28")>  _
        Public Property door_loc() As Global.System.Drawing.Size
            Get
                Return CType(Me("door_loc"),Global.System.Drawing.Size)
            End Get
            Set
                Me("door_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("53, 39")>  _
        Public Property door_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("door_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("door_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13, 150")>  _
        Public Property logtable_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("logtable_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("logtable_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("43, 61")>  _
        Public Property logtable_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("logtable_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("logtable_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("71, 29")>  _
        Public Property counter_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("counter_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("counter_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("52, 85")>  _
        Public Property counter_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("counter_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("counter_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("144, 235")>  _
        Public Property librarian1_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("librarian1_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("librarian1_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("130, 99")>  _
        Public Property librarian1_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("librarian1_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("librarian1_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13, 254")>  _
        Public Property librarian2_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("librarian2_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("librarian2_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("79, 62")>  _
        Public Property librarian2_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("librarian2_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("librarian2_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("482, 235")>  _
        Public Property librarian3_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("librarian3_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("librarian3_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("225, 99")>  _
        Public Property librarian3_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("librarian3_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("librarian3_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("288, 309")>  _
        Public Property bookshelf1_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("bookshelf1_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("bookshelf1_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("146, 25")>  _
        Public Property bookshelf1_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("bookshelf1_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("bookshelf1_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("288, 29")>  _
        Public Property bookshelf2_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("bookshelf2_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("bookshelf2_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("146, 29")>  _
        Public Property bookshelf2_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("bookshelf2_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("bookshelf2_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("440, 29")>  _
        Public Property opac_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("opac_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("opac_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("36, 29")>  _
        Public Property opac_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("opac_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("opac_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("482, 29")>  _
        Public Property pcsection_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("pcsection_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("pcsection_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("221, 38")>  _
        Public Property pcsection_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("pcsection_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("pcsection_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("709, 29")>  _
        Public Property thesaurus_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("thesaurus_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("thesaurus_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("32, 29")>  _
        Public Property thesaurus_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("thesaurus_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("thesaurus_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("836, 30")>  _
        Public Property bookssection1_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("bookssection1_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("bookssection1_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("137, 137")>  _
        Public Property bookssection1_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("bookssection1_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("bookssection1_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("836, 197")>  _
        Public Property bookssection2_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("bookssection2_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("bookssection2_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("137, 137")>  _
        Public Property bookssection2_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("bookssection2_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("bookssection2_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13, 235")>  _
        Public Property divider_loc() As Global.System.Drawing.Point
            Get
                Return CType(Me("divider_loc"),Global.System.Drawing.Point)
            End Get
            Set
                Me("divider_loc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("125, 20")>  _
        Public Property divider_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("divider_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("divider_size") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.NoiseDetect.My.MySettings
            Get
                Return Global.NoiseDetect.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
